#!/bin/bash
IFS='.' read -r -a val <<< "$(xbacklight -get)"
if   [ $val -le 15 ]  ; then brightness=" $val" ;
elif [ $val -le 65 ]  ; then brightness=" $val" ;
elif [ $val -le 100 ] ; then brightness=" $val" ;
fi
echo $brightness
